# docker-compose.yml
version: '3.8'

services:
  f1-optimizer:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./default_data:/app/default_data
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-your-secret-key-here}
    restart: unless-stopped
