# docker-compose.yml
version: '3.8'

services:
  f1-optimizer:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./default_data:/app/default_data
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-your-secret-key-here}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-your-google-client-id}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-your-google-client-secret}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID:-your-facebook-client-id}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET:-your-facebook-client-secret}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-your-github-client-id}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-your-github-client-secret}
      - ADMIN_EMAILS=${ADMIN_EMAILS:-admin@example.com}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-f1db}
      - POSTGRES_USER=${POSTGRES_USER:-f1user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-f1pass}
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-f1user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-f1pass}
      POSTGRES_DB: ${POSTGRES_DB:-f1db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
